title: 茶瓜客
author: 茶瓜客
subtitle: 解衣又作茶瓜客，倚槛同看烟雨峰

url: "https://www.chaguake.com"
baseurl: ""

footer_only_homepage: true
footer_url: "https://github.com/rahul-bothra"
footer_text: "Theme by rahul-bothra"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "标签"
   link: "tags/index.html"
 - name: "关于"
   link: "about/index.html"

